<a href="https://colab.research.google.com/github/ARL4514/Kecerdasan-Buatan/blob/Jobsheet-1/JOBSHEET02_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

JOBSHEET 2
OPERASI MATEMATIKA, VEKTOR, DAN MATRIKS


LATIHAN

1. Tipe Data Python

a. Cek Tipe Data

In [ ]:
# Cek Tipe Data
var = 123
print(type(var))

<class 'int'>


b. Tipe Data String

In [ ]:
# Tipe data String
a = '123'
b = '3.4'
c = "Data String"
print(type(c))

<class 'str'>


c. Tipe Data Numerik

In [ ]:
# Tipe data numerik
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)
sum = var1 + var2
print(sum)
var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)

<class 'float'>
345.0
379.5
34
12


d. Tipe Data Boolean

In [ ]:
# Tipe Data Boolean
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

False
False
True
True


e. Tipe Data List

In [ ]:
# Tipe Data List
list = ["belajar dasar python", 2023, 3.8, True]
print(list)
print(list[3])
print(list[1:3])
print(len(list))

['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


2. Operasi Matematika menggunakan Python

a. Mendapatkan nilai minimum dan maksimum

In [ ]:
x_min = min(5, 10, 25)
y_max = max(6, 12, 18)
print("Nilai minimum:", x_min)
print("Nilai maksimum:", y_max)

Nilai minimum: 5
Nilai maksimum: 18


b. Mendapatkan nilai absolut

In [ ]:
x_abs = abs(-7.25)
print("Nilai absolut:", x_abs)

Nilai absolut: 7.25


c. Mendapatkan nilai pangkat

In [ ]:
import math
x_pow = math.pow(4, 3)
print("Hasil 4 pangkat 3:", x_pow)

Hasil 4 pangkat 3: 64.0


d. Mendapatkan nilai akar

In [ ]:
import math
x_sqrt = math.sqrt(64)
print("Akar dari 64:", x_sqrt)

Akar dari 64: 8.0


e. Mendapatkan nilai pembulatan

In [ ]:
import math
x_ceil = math.ceil(1.4)
y_floor = math.floor(1.4)
print("Pembulatan ke atas (1.4):", x_ceil)
print("Pembulatan ke bawah (1.4):", y_floor)

Pembulatan ke atas (1.4): 2
Pembulatan ke bawah (1.4): 1


f. Mendapatkan nilai konstanta(PI)

In [ ]:
import math
x_pi = math.pi
print("Nilai PI:", x_pi)

Nilai PI: 3.141592653589793


3. Menggunakan Fungsi MATH

In [ ]:
import math

# Contoh penggunaan fungsi math
print("math.sin(0):", math.sin(0))                # Sinus
print("math.cos(0):", math.cos(0))                # Cosinus
print("math.tan(0):", math.tan(0))                # Tangen
print("math.log(10):", math.log(10))              # Logaritma natural
print("math.log10(10):", math.log10(10))          # Logaritma basis 10
print("math.degrees(math.pi):", math.degrees(math.pi)) # Konversi radian ke derajat
print("math.dist([0,0], [3,4]):", math.dist([0,0], [3,4])) # Jarak Euclidean
print("math.factorial(5):", math.factorial(5))    # Faktorial
print("math.fmod(10, 3):", math.fmod(10, 3))      # Sisa pembagian (float)
print("math.isnan(float('nan')):", math.isnan(float('nan'))) # Cek apakah NaN
print("math.gamma(5):", math.gamma(5))            # Fungsi Gamma
print("math.perm(5, 2):", math.perm(5, 2))        # Permutasi

math.sin(0): 0.0
math.cos(0): 1.0
math.tan(0): 0.0
math.log(10): 2.302585092994046
math.log10(10): 1.0
math.degrees(math.pi): 180.0
math.dist([0,0], [3,4]): 5.0
math.factorial(5): 120
math.fmod(10, 3): 1.0
math.isnan(float('nan')): True
math.gamma(5): 24.0
math.perm(5, 2): 20


4. Operasi Matriks dan vektor dengan python

a. Membuat Matriks di python

In [ ]:
import numpy as np
A = np.array([[80, 30, 25], [50, 20, 10]])
B = np.array([[30, 60, 15], [10, 30, 30]])
hasil = A + B
print("Hasil Penjumlahan Matriks A + B:")
print(hasil)

Hasil Penjumlahan Matriks A + B:
[[110  90  40]
 [ 60  50  40]]


b. Melakukan operasi dot product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])
hasil = np.dot(A, B)
print("hasil: ", hasil)

hasil:  2025


c. Melakukan operasi cross product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])
Hasil = np.cross(A, B)
print("hasil: ", hasil)

hasil:  2025


TUGAS PRAKTIKUM

1. Perkalian Matriks

In [ ]:
import numpy as np

# Mendefinisikan matriks A, B, dan C
A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

# Perkalian Matriks A x B
hasil_AB = np.dot(A, B) # Menggunakan fungsi dot product sesuai modul [cite: 171]

# Perkalian Matriks B x C
hasil_BC = np.dot(B, C)

print("Hasil A x B:\n", hasil_AB)
print("Hasil B x C:\n", hasil_BC)

Hasil A x B:
 [[7 2]
 [4 2]]
Hasil B x C:
 [[ 0  2  3]
 [-3  1  3]]


2. Operasi Faktorial

In [ ]:
import math

# Menghitung 6!
faktorial_6 = math.factorial(6) # Menggunakan fungsi math.factorial()

# Menghitung 8! / 5!
faktorial_gabungan = math.factorial(8) / math.factorial(5)

print("Nilai 6! =", faktorial_6)
print("Nilai 8! / 5! =", faktorial_gabungan)

Nilai 6! = 720
Nilai 8! / 5! = 336.0


3. Analisis Vektor 3D

In [ ]:
import numpy as np

# Mendefinisikan vektor dalam array 3D [cite: 169]
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Menghitung panjang vektor (Norm)
# Rumus: sqrt(sum(x^2))
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Perkalian Titik (Dot Product)
dot_AB = np.dot(A, B) # Sesuai contoh pada baris [cite: 171]

# Perkalian Silang (Cross Product)
cross_AB = np.cross(A, B) # Sesuai contoh pada baris [cite: 180]

print(f"Panjang Vektor A: {panjang_A:.2f}")
print(f"Panjang Vektor B: {panjang_B:.2f}")
print(f"Hasil A . B: {dot_AB}")
print(f"Hasil A x B: {cross_AB}")

Panjang Vektor A: 9.11
Panjang Vektor B: 12.41
Hasil A . B: 58
Hasil A x B: [ 24  79 -51]
